# Generated by Django 6.0.5 on 2026-05-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_sale_saleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
