# Generated by Django 6.0.5 on 2026-05-22 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart_of_accounts', '0002_seed_default_accounts'),
        ('journal', '0004_purchase_purchaseitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('voucher_no', models.CharField(max_length=50, unique=True)),
                ('narration', models.TextField(blank=True, null=True)),
                ('mode', models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank'), ('Credit', 'Credit')], default='Cash', max_length=20)),
                ('gst_applicable', models.BooleanField(default=True)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('round_off_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('round_off_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_returns', to='chart_of_accounts.chartofaccount')),
                ('journal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_return', to='journal.journal')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SalesReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.CharField(max_length=150)),
                ('batch', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry', models.DateField(blank=True, null=True)),
                ('hsn', models.CharField(blank=True, max_length=50, null=True)),
                ('qty', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sales_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='journal.salesreturn')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
