# Generated by Django 6.0.5 on 2026-05-22 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart_of_accounts', '0002_seed_default_accounts'),
        ('journal', '0007_receipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('voucher_no', models.CharField(max_length=50, unique=True)),
                ('narration', models.TextField(blank=True, null=True)),
                ('mode', models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank / Cheque')], default='Cash', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='journal.journal')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='chart_of_accounts.chartofaccount')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
