# Generated by Django 6.0.5 on 2026-05-22 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('voucher_no', models.CharField(max_length=50, unique=True)),
                ('narration', models.TextField(blank=True, null=True)),
                ('direction', models.CharField(choices=[('Bank to Cash', 'Bank -> Cash (withdraw)'), ('Cash to Bank', 'Cash -> Bank (deposit)')], default='Bank to Cash', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('round_off_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('round_off_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contra', to='journal.journal')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
