from django.urls import path

from .views import (
    contra_detail,
    contras,
    create_journal,
    expense_detail,
    expenses,
    journals,
    payment_detail,
    payments,
    purchase_detail,
    purchase_return_detail,
    purchase_returns,
    purchases,
    receipt_detail,
    receipts,
    sale_detail,
    sales,
    sales_return_detail,
    sales_returns,
)


urlpatterns = [
    path('journal', journals, name='journals_no_slash'),
    path('journal/', journals, name='journals'),
    path('journals', journals, name='journal_list_no_slash'),
    path('journals/', journals, name='journal_list'),
    path('journals/create', create_journal, name='create_journal'),
    path('journals/create/', create_journal, name='create_journal_slash'),
    path('sales', sales, name='sales'),
    path('sales/', sales, name='sales_slash'),
    path('sales/create', sales, name='sales_create'),
    path('sales/create/', sales, name='sales_create_slash'),
    path('sales/<int:sale_id>', sale_detail, name='sale_detail'),
    path('sales/<int:sale_id>/', sale_detail, name='sale_detail_slash'),
    path('purchases', purchases, name='purchases'),
    path('purchases/', purchases, name='purchases_slash'),
    path('purchase/create', purchases, name='purchases_create'),
    path('purchase/create/', purchases, name='purchases_create_slash'),
    path('purchases/<int:purchase_id>', purchase_detail, name='purchase_detail'),
    path('purchases/<int:purchase_id>/', purchase_detail, name='purchase_detail_slash'),
    path('sales_returns', sales_returns, name='sales_returns'),
    path('sales_returns/', sales_returns, name='sales_returns_slash'),
    path('sales_returns/create', sales_returns, name='sales_returns_create'),
    path('sales_returns/create/', sales_returns, name='sales_returns_create_slash'),
    path('sales_returns/<int:sales_return_id>', sales_return_detail, name='sales_return_detail'),
    path('sales_returns/<int:sales_return_id>/', sales_return_detail, name='sales_return_detail_slash'),
    path('purchase_returns', purchase_returns, name='purchase_returns'),
    path('purchase_returns/', purchase_returns, name='purchase_returns_slash'),
    path('purchase_returns/create', purchase_returns, name='purchase_returns_create'),
    path('purchase_returns/create/', purchase_returns, name='purchase_returns_create_slash'),
    path('purchase_returns/<int:purchase_return_id>', purchase_return_detail, name='purchase_return_detail'),
    path('purchase_returns/<int:purchase_return_id>/', purchase_return_detail, name='purchase_return_detail_slash'),
    path('receipts', receipts, name='receipts'),
    path('receipts/', receipts, name='receipts_slash'),
    path('receipts/create', receipts, name='receipts_create'),
    path('receipts/create/', receipts, name='receipts_create_slash'),
    path('receipt/create', receipts, name='receipt_create'),
    path('receipt/create/', receipts, name='receipt_create_slash'),
    path('receipts/<int:receipt_id>', receipt_detail, name='receipt_detail'),
    path('receipts/<int:receipt_id>/', receipt_detail, name='receipt_detail_slash'),
    path('payments', payments, name='payments'),
    path('payments/', payments, name='payments_slash'),
    path('payments/create', payments, name='payments_create'),
    path('payments/create/', payments, name='payments_create_slash'),
    path('payments/<int:payment_id>', payment_detail, name='payment_detail'),
    path('payments/<int:payment_id>/', payment_detail, name='payment_detail_slash'),
    path('expenses', expenses, name='expenses'),
    path('expenses/', expenses, name='expenses_slash'),
    path('expenses/create', expenses, name='expenses_create'),
    path('expenses/create/', expenses, name='expenses_create_slash'),
    path('expenses/<int:expense_id>', expense_detail, name='expense_detail'),
    path('expenses/<int:expense_id>/', expense_detail, name='expense_detail_slash'),
    path('contras', contras, name='contras'),
    path('contras/', contras, name='contras_slash'),
    path('contras/create', contras, name='contras_create'),
    path('contras/create/', contras, name='contras_create_slash'),
    path('contras/<int:contra_id>', contra_detail, name='contra_detail'),
    path('contras/<int:contra_id>/', contra_detail, name='contra_detail_slash'),
]
